### ISSUE TITLE
自动切换分 P 后插件失效

### ISSUE THREAD

**Issue by wlkz** [fython/userscript-enhance-bilibili-player#16]
在 v0.2.0 中以后手动切换分 P 后插件失效的问题已经解决，但自动切换分 P 后插件仍然失效。

复现步骤：

1. 随意点开一个番剧
2. 进度条拖到最后让播放器自动切换分 P

**Comment by fython** [comment]
感谢反馈！

**Comment by fython** [comment]
问题已在 v0.2.2 修复。
