### ISSUE TITLE
兼容其他插件 Xmader/bilitwin

### ISSUE THREAD

**Issue by fython** [fython/userscript-enhance-bilibili-player#17]
用户反馈需要改善兼容，目前未测试兼容问题。

插件项目：<https://github.com/Xmader/bilitwin>

**Comment by Geeyun-JY3** [comment]
作者你好我是当时反馈希望兼容该插件的用户，目前我亲测的兼容问题有：
1. 普通投稿视频本插件无法与该插件共存；
2. 番剧影视第一次右键可以和该插件共存，第二次右键该插件菜单消失，本插件仍生效但重复显示。
附图：
第一次右键：
![image](https://user-images.githubusercontent.com/49396421/84002093-728b2200-a99a-11ea-803f-55d962a7146a.png)

第二次右键：
![image](https://user-images.githubusercontent.com/49396421/84002717-6fdcfc80-a99b-11ea-8e00-f04a8fda13ca.png)

**Comment by fython** [comment]
@Geeyun-JY3 感谢详细的反馈，很抱歉最近还没有开始处理，有时间我会尽快修复

**Comment by Geeyun-JY3** [comment]
@fython 没事不急的，我也是有空做个补充。

**Comment by fython** [comment]
我自己的测试的情况如下：

同时开启 [fython/userscript-enhance-bilibili-player](https://github.com/fython/userscript-enhance-bilibili-player)（版本 0.2.1）和 [Xmader/bilitwin](https://github.com/Xmader/bilitwin)（版本 1.23.13）时

![](https://user-images.githubusercontent.com/3166782/84584207-f0847880-ae33-11ea-8b5d-7de30a90f7d2.png)

视频播放器菜单中只显示了 bilitwin 插件的增强菜单项，未正常显示 userscript-enhance-bilibili-player 插件的菜单项。

![](https://user-images.githubusercontent.com/3166782/84584223-1d389000-ae34-11ea-90f5-7df75b612c24.png)

## 修复进展

### 插入菜单原理

userscript-enhance-bilibili-player 使用 `MutationObserver` 对 `div.bilibili-player-context-menu-container.black.bilibili-player-context-menu-origin` 元素（播放器菜单列表）进行监听 attributes 变化判断是否正在显示。

通常要等待第一次显示之后才插入插件菜单，否则无法正确插入并显示插件菜单部分。

### 可能原因

最初的插件版本并不判断菜单中是否已有插件菜单项，而是每次在菜单隐藏之后将播放器菜单列表的元素清除。

后续版本已经改进但直至 0.2.1 才把每次菜单隐藏清空列表元素的一行 `clear()` 去掉，这一行可能会导致无法与其他插件共存。

目前在我的浏览器上的测试情况是共存时 bilitwin 插件可以正常使用，userscript-enhance-bilibili-player 插件无法使用。

**Comment by Geeyun-JY3** [comment]
最近发现好像兼容了，普通视频能调出菜单。不清楚 Xmader/bilitwin 开发者是否进行了兼容（commit 标题并没有写）
功能未完备测试。

**Comment by Geeyun-JY3** [comment]
额今天测试好像又不兼容了（看来 Xmader/bilitwin 当时没兼容🌚

**Comment by fython** [comment]
计划重构后再重新收集兼容问题，此 Issue 先关闭。

**Comment by Geeyun-JY3** [comment]
这两年破站改动非常多，该脚本也已停更并失效，重构完后其实不需要考虑兼容这个脚本的事了。
