### ISSUE TITLE
新的时间跳转参数：`?start_progress=[毫秒数]`

### ISSUE THREAD

**Issue by Geeyun-JY3** [fython/userscript-enhance-bilibili-player#26]
今天在这个 [活动页](https://www.bilibili.com/blackboard/topic/activity-NZd9XjWOd.html) 发现一个新的时间跳转参数：`?start_progress=[微秒数]`，好像只作用于番剧／放映厅。且跳转优先级好像高于现有插件时间格式

只在以下这两个播放页 URL 格式粗略测试过，即 `'*://www.bilibili.com/bangumi/play/ep*'` 和 `'*://www.bilibili.com/bangumi/play/ss*'`。

**Comment by fython** [comment]
结合 #27 （清理地址参数的需求）来看，我更倾向于清除掉 `start_progress` 的参数，然后保持使用 `t` 参数。

**Comment by Geeyun-JY3** [comment]
主要是考虑到这个是微秒数，会更精确🌝

**Comment by fython** [comment]
@Geeyun-JY3 已于 0.3.0 支持 start_progress 毫秒数参数，目前观察在绝大部分视频播放页面下都可用，所以不做额外判断了。由于毫秒跳转并不支持 Human-readable 的传值，选项默认关闭。

**Comment by Geeyun-JY3** [comment]
才发现之前写错了，应该是毫秒🤦‍♂️
不过今天确认该参数已经失效（应该有好一段时间了）。
