### ISSUE TITLE
视频评论定位参数及网址跟踪参数清理建议

### ISSUE THREAD

**Issue by Geeyun-JY3** [fython/userscript-enhance-bilibili-player#27]
- 如果通过评论定位链接打开视频后复制当前播放位置的视频链接，如打开 https://www.bilibili.com/video/av328585898#reply3062673610 后复制链接会得到如 https://www.bilibili.com/video/av328585898?t=12s#reply3062673610 的链接
- 如视频网址跟踪参数未清理，那么复制得到的当前播放位置的视频链接会很长，如 `https://www.bilibili.com/video/av21322566/?spm_id_from=333.788.recommend_more_video.3&t=15s`。（不过这个其实我没什么所谓，因为我一直开着 [Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved) 这个插件的 `网址参数清理功能`）

针对以上两点，如果需求就是定位视频播放位置，那建议脚本去除无用参数后再往网址里添加时间戳，有用的参数我能想到的好像就只有分 P 了。无用参数我知道的有：评论定位参数、跟踪参数

**Comment by fython** [comment]
感谢反馈，复制地址时清理参数确实是很实用的功能，下个版本会做。

**Comment by fython** [comment]
@Geeyun-JY3 已于 0.3.0 版本中支持，清理参数选项默认开启。同时，无论是否开启清理选项都会清理 Hash。
