### ISSUE TITLE
添加番剧页面的支持

### ISSUE THREAD

**Issue by wlkz** [fython/userscript-enhance-bilibili-player#7]
大概像 `https://www.bilibili.com/bangumi/play/ep*` 这种

**Comment by fython** [comment]
已在 0.1.9 版本修复，感谢反馈。

**Comment by wlkz** [comment]
现在还是有某些页面没有匹配上😂，感觉可以参考下 [解除B站区域限制](https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.md) 的匹配列表，那个目测比较全

**Comment by fython** [comment]
> 现在还是有某些页面没有匹配上😂，感觉可以参考下 [解除B站区域限制](https://github.com/ipcjs/bilibili-helper/blob/user.js/bilibili_bangumi_area_limit_hack.md) 的匹配列表，那个目测比较全

刚刚才注意到，我再补充一下。
